services:
    kolyya_photo.twig.extension:
        class: Kolyya\PhotoBundle\Twig\Extension\PhotoExtension
        public: false
        arguments: [ '@kolyya_photo.templating.helper' ]
        tags:
            - { name: twig.extension }